# Generated by Django 3.0.4 on 2020-04-12 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('the_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_raised', models.DateField(auto_now_add=True)),
                ('issue', models.CharField(max_length=300)),
                ('in_progress', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution', models.CharField(max_length=300)),
                ('date_closed', models.DateField()),
                ('log_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='raise_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
