# Generated by Django 3.0.4 on 2020-04-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_list', '0002_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
