# Generated by Django 3.0.4 on 2020-04-02 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('the_list', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, verbose_name='account_activation_token')),
                ('date_invited', models.DateTimeField(auto_now_add=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('invite_used', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('invite_to_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='the_list.ShopGroup')),
                ('registrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_used', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
